name: Deploy website to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: website
        run: npm ci

      - name: Build website
        working-directory: website
        env:
          VITE_API_BASE: ${{ vars.VITE_API_BASE }}
          VITE_FW_BASE: ${{ vars.VITE_FW_BASE }}
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
          force_orphan: true

